Repository boostcampwm-2024/web12-MafiaCamp, pull requests merged in 2024-11, with the labels that each got.

#45 [ui] MafiaCamp 웹 사이트 UI 구현
  FE/.eslintrc.json
  FE/.prettierrc
  FE/next.config.ts
  FE/package-lock.json
  FE/package.json
  FE/public/common/google-icon.png
  FE/public/common/kakao-talk-icon.png
  FE/public/common/mafiacamp-logo-large.png
  FE/public/common/mafiacamp-logo-small.png
  FE/public/file.svg
  FE/public/globe.svg
  FE/public/home/citizen.png
  FE/public/home/doctor.png
  FE/public/home/mafia.png
  FE/public/home/police.png
  FE/public/lottie/404.json
  FE/public/lottie/500.json
  FE/public/lottie/global.json
  FE/public/lottie/star.json
  FE/public/lottie/video.json
  FE/public/lottie/welcome.json
  FE/public/next.svg
  FE/public/vercel.svg
  FE/public/window.svg
  FE/src/app/error.tsx
  FE/src/app/favicon.ico
  FE/src/app/fonts/GeistMonoVF.woff
  FE/src/app/fonts/GeistVF.woff
  FE/src/app/globals.css
  FE/src/app/introduction/page.tsx
  FE/src/app/layout.tsx
  FE/src/app/lobby/[id]/page.tsx
  FE/src/app/lobby/page.tsx
  FE/src/app/not-found.tsx
  FE/src/app/page.tsx
  FE/src/app/signin/page.tsx
  FE/src/components/common/Background.tsx
  FE/src/components/common/FloatingButton.tsx
  FE/src/components/common/Footer.tsx
  FE/src/components/common/Header.tsx
  FE/src/components/common/icons/CheckCircleIcon.tsx
  FE/src/components/common/icons/ChevronUpIcon.tsx
  FE/src/components/common/icons/PaperAirplainIcon.tsx
  FE/src/components/common/icons/UsersIcon.tsx
  FE/src/components/home/Introduction.tsx
  FE/src/components/home/RoleInfo.tsx
  FE/src/components/home/RuleInfo.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/room/ChattingItem.tsx
  FE/src/components/lobby/room/ChattingList.tsx
  FE/src/components/signin/SigninPanel.tsx
  FE/src/styles/globals.css
  FE/tailwind.config.ts
Labels: fe, D-3, ui, chore

#79 [Fix] eslint 버전간의 호환성 문제 해결
  BE/.eslintrc.js
  BE/package-lock.json
  BE/package.json
Labels: fix, be, D-0

#83 [Feat]: openvidu 설치
  openvidu/.env
  openvidu/certificates/live/certificates.conf
  openvidu/certificates/live/localhost/fullchain.pem
  openvidu/certificates/live/localhost/privkey.pem
  openvidu/coturn/shared-secret-key
  openvidu/custom-nginx-vhosts/default.conf
  openvidu/docker-compose.override.yml
  openvidu/docker-compose.yml
  openvidu/openvidu
Labels: be, D-1, feat

#81 [UI] 화상 인터페이스 UI 구현
  FE/package-lock.json
  FE/package.json
  FE/src/app/layout.tsx
  FE/src/app/lobby/[id]/page.tsx
  FE/src/components/common/icons/ChatBubbleIcon.tsx
  FE/src/components/common/icons/CloseIcon.tsx
  FE/src/components/common/icons/PlayIcon.tsx
  FE/src/components/common/icons/UsersIcon.tsx
  FE/src/components/common/icons/VideoCameraIcon.tsx
  FE/src/components/common/icons/VideoCameraSlashIcon.tsx
  FE/src/components/lobby/room/Bottombar.tsx
  FE/src/components/lobby/room/ChattingList.tsx
  FE/src/components/lobby/room/VideoItem.tsx
  FE/src/components/lobby/room/VideoViewer.tsx
  FE/src/stores/sidebarStore.ts
Labels: fe, D-2, ui, chore

#80 [Feat] TypeORM 환경 설정 및 서버시작 시 TABLE 생성 SQL가 동작하게 구성
  BE/.gitignore
  BE/package-lock.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/common/config/typeorm.config.ts
  BE/src/common/sql/schema.sql
  BE/src/main.ts
Labels: be, D-3, feat

#82 [Feat] 게임방 세션 관리 기능 구현
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/config/typeorm.config.ts
  BE/src/events/events.gateway.ts
  BE/src/events/events.module.ts
  BE/src/events/wss.ts
  BE/src/rooms/dto/create-room.dto.ts
  BE/src/rooms/room.model.ts
  BE/src/rooms/rooms.module.ts
  BE/src/rooms/rooms.service.ts
  docs/web12-기획공유발표자료.pdf
Labels: be, D-2, feat

#84 [Feat] 유저에게 직업 할당 로직 구현과 User 모듈, GameUser 모듈, GameHistory 모듈 아키텍처 구현
  BE/.gitignore
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/config/typeorm.config.ts
  BE/src/common/error/error.code.ts
  BE/src/common/error/error.message.ts
  BE/src/common/error/game.invalid.player.count.error.ts
  BE/src/common/error/not.found.game-user.error.ts
  BE/src/common/error/not.found.game.history.error.ts
  BE/src/common/error/not.found.user.error.ts
  BE/src/common/error/role.count.negative.error.ts
  BE/src/common/sql/schema.sql
  BE/src/game-user/enitity/game.user.entity.ts
  BE/src/game-user/enitity/game.user.result.ts
  BE/src/game-user/game-user.module.ts
  BE/src/game-user/game-user.service.ts
  BE/src/game-user/repository/game-user.repository.ts
  BE/src/game-user/repository/typeorm.game-user.repository.ts
  BE/src/game-user/usecase/find.game-user.usecase.ts
  BE/src/game-user/usecase/register.game-user.usecase.ts
  BE/src/game/dto/allocate.job.request.ts
  BE/src/game/dto/allocate.job.response.ts
  BE/src/game/entity/game.history.entity.ts
  BE/src/game/entity/game.history.result.ts
  BE/src/game/entity/game.status.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/game/job.factory.ts
  BE/src/game/mafia.role.ts
  BE/src/game/random.job.factory.ts
  BE/src/game/repository/game.history.repository.ts
  BE/src/game/repository/typeorm.game.history.repository.ts
  BE/src/game/usecase/allocate.user.role.usecase.ts
  BE/src/user/dto/find-user.request.ts
  BE/src/user/dto/register-user.request.ts
  BE/src/user/entity/user.entity.ts
  BE/src/user/repository/typeorm.user.repository.ts
  BE/src/user/repository/user.repository.ts
  BE/src/user/usecase/find.user.usecase.ts
  BE/src/user/usecase/register.user.usecase.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: be, D-2, feat

#85 [Feat] 예외 변경과 글로벌 예외 처리
  BE/.gitignore
  BE/src/common/error/error.code.ts
  BE/src/common/error/error.message.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/game.invalid.player.count.error.ts
  BE/src/common/error/game.invalid.player.count.exception.ts
  BE/src/common/error/not.found.game-user.error.ts
  BE/src/common/error/not.found.game-user.exception.ts
  BE/src/common/error/not.found.game.history.error.ts
  BE/src/common/error/not.found.game.history.exception.ts
  BE/src/common/error/not.found.user.error.ts
  BE/src/common/error/not.found.user.exception.ts
  BE/src/common/error/role.count.negative.error.ts
  BE/src/common/error/role.count.negative.exception.ts
  BE/src/common/filter/global.exception.filter.ts
  BE/src/game-user/repository/typeorm.game-user.repository.ts
  BE/src/game/random.job.factory.ts
  BE/src/game/repository/typeorm.game.history.repository.ts
  BE/src/main.ts
  BE/src/user/repository/typeorm.user.repository.ts
Labels: be, D-3, feat

#87 [Feat] OpenVidu NestJS 환경설정 및 SSL 인증서 발급
  BE/.gitignore
  BE/package-lock.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/main.ts
  BE/src/openvidu/openvidu.controller.spec.ts
  BE/src/openvidu/openvidu.controller.ts
  BE/src/openvidu/openvidu.module.ts
  BE/src/openvidu/openvidu.service.spec.ts
  BE/src/openvidu/openvidu.service.ts
  openvidu/.gitignore
  openvidu/certificates/live/certificates.conf
  openvidu/certificates/live/localhost/fullchain.pem
  openvidu/certificates/live/localhost/privkey.pem
Labels: be, D-2, feat

#88 [Feat] winston을 활용한 로키 스택 스키마 로거 구현
  BE/.prettierrc
  BE/package-lock.json
  BE/package.json
  BE/src/app.controller.spec.ts
  BE/src/app.controller.ts
  BE/src/app.module.ts
  BE/src/app.service.ts
  BE/src/common/logger/basic.logger.interceptor.ts
  BE/src/common/logger/http.logger.interceptor.ts
  BE/src/common/logger/logger.module.ts
  BE/src/common/logger/sanitize.data.ts
  BE/src/common/logger/trace.middleware.ts
  BE/src/common/logger/websocket.logger.interceptor.ts
  BE/src/common/logger/winston.config.ts
  BE/src/common/typeorm/typeorm.config.ts
  BE/src/game-user/enitity/game-user.entity.ts
  BE/src/game-user/enitity/game-user.result.ts
  BE/src/game-user/game-user.module.ts
  BE/src/game-user/game-user.service.ts
  BE/src/game-user/repository/game-user.repository.ts
  BE/src/game-user/repository/typeorm.game-user.repository.ts
  BE/src/game-user/usecase/find.game-user.usecase.ts
  BE/src/game-user/usecase/register.game-user.usecase.ts
  BE/src/game/dto/allocate.job.response.ts
  BE/src/game/entity/game-history.entity.ts
  BE/src/game/entity/game-history.result.ts
  BE/src/game/entity/game-status.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/game/job.factory.ts
  BE/src/game/mafia-role.ts
  BE/src/game/random.job.factory.ts
  BE/src/game/repository/game-history.repository.ts
  BE/src/game/repository/typeorm.game-history.repository.ts
  BE/src/game/usecase/allocate.user-role.usecase.ts
  BE/src/user/dto/find-user.request.ts
  BE/src/user/entity/user.entity.ts
  BE/src/user/repository/typeorm.user.repository.ts
  BE/src/user/user.module.ts
Labels: be, D-2, feat

#92 [Feat] OpenVidu 모듈 추상화 및 service 계층 작성
  BE/src/app.module.ts
  BE/src/openvidu/openvidu.controller.spec.ts
  BE/src/openvidu/openvidu.controller.ts
  BE/src/openvidu/openvidu.module.ts
  BE/src/openvidu/openvidu.service.spec.ts
  BE/src/openvidu/openvidu.service.ts
  BE/src/video-server/implementations/openvidu.service.ts
  BE/src/video-server/types/session-participant.type.ts
  BE/src/video-server/usecase/video-server.usecase.ts
  BE/src/video-server/video-server.controller.spec.ts
  BE/src/video-server/video-server.controller.ts
  BE/src/video-server/video-server.module.ts
  BE/src/video-server/video-server.service.spec.ts
Labels: be, D-1, feat

#86 [Feat] 방 생성 시 방 이름, 인원 수를 설정하는 기능 구현
  FE/package-lock.json
  FE/package.json
  FE/public/lottie/no_data.json
  FE/src/app/error.tsx
  FE/src/app/game/[id]/page.tsx
  FE/src/app/introduction/page.tsx
  FE/src/app/layout.tsx
  FE/src/app/lobby/[id]/page.tsx
  FE/src/app/lobby/page.tsx
  FE/src/app/not-found.tsx
  FE/src/app/signin/page.tsx
  FE/src/components/common/FloatingButton.tsx
  FE/src/components/common/Footer.tsx
  FE/src/components/common/Header.tsx
  FE/src/components/common/HeaderSidebar.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/ChattingItem.tsx
  FE/src/components/game/ChattingList.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/home/Introduction.tsx
  FE/src/components/home/RoleInfo.tsx
  FE/src/components/home/RuleInfo.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/lobby/room/VideoViewer.tsx
  FE/src/components/signin/SigninPanel.tsx
  FE/src/hooks/useDragScroll.ts
  FE/src/libs/zod/roomCreateFormSchema.ts
  FE/src/stores/sidebarStore.ts
Labels: fe, D-2, feat, ui, rename

#96 [Refactor] Openvidu service 계층 리팩토링
  BE/src/video-server/implementations/openvidu.service.ts
  BE/src/video-server/types/openvidu.type.ts
Labels: be, D-0, refactor

#91 [Feat] 방 목록 조회 & 게임방 입장 기능
  FE/src/components/game/ChattingList.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/constants/roomStatus.ts
  FE/src/stores/socketStore.ts
  FE/src/types/chat.ts
  FE/src/types/room.ts
Labels: fe, D-2, feat

#97 [Feat] OpenVidu 연결 & 카메라 on/off 기능 & CI/CD 구축
  .github/workflows/deploy_FE.yml
  FE/.dockerignore
  FE/.gitignore
  FE/Dockerfile
  FE/src/app/game/[id]/page.tsx
  FE/src/app/game/[roomId]/page.tsx
  FE/src/components/common/Header.tsx
  FE/src/components/common/HeaderSidebar.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/ChattingList.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/home/Introduction.tsx
  FE/src/components/home/RoleInfo.tsx
  FE/src/components/home/RuleInfo.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/hooks/useDragScroll.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/stores/socketStore.ts
Labels: fe, D-1, feat, refactor

#120 [Feat] Back-end CI/CD 구축
  .github/workflows/deploy.yml
Labels: be, D-0, feat

#116 [Feat] CountDownTimer 구현
  BE/package-lock.json
  BE/src/common/error/duplicate.timer.exception.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/not.found.timer.exception.ts
  BE/src/common/logger/basic.logger.interceptor.ts
  BE/src/common/typeorm/typeorm.config.ts
  BE/src/game/countdown.timer.ts
  BE/src/game/dto/start.countdown.request.ts
  BE/src/game/dto/stop.countdown.request.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/game/mafia.countdown.timer.ts
  BE/src/game/timeout.situation.ts
  BE/src/game/usecase/countdown.timeout.usecase.ts
  BE/src/main.ts
Labels: be, D-1, feat

#115 [Feat] 게임 대기 시 참가자 목록 표시 & 채팅 UI 수정 & 닉네임 설정 기능
  .github/workflows/deploy_FE.yml
  FE/src/app/game/[roomId]/page.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/ChattingItem.tsx
  FE/src/components/game/ChattingList.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/lobby/NicknameModal.tsx
  FE/src/hooks/useOpenVidu.ts
  FE/src/stores/socketStore.ts
Labels: fix, fe, D-2, feat, ui

#117 [Feat] openvidu 세션 연결 종료 메소드 구현
  BE/src/video-server/implementations/openvidu.service.ts
Labels: be, D-3

#121 [Fix] CI/CD 과정 중 TypeScript 컴파일 체크 오류
  BE/package.json
Labels: fix, be, D-0

#122 [Feat] 실시간 투표 기능 추가
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/not.found.ballot-box.exception.ts
  BE/src/common/error/not.found.game-room.exception.ts
  BE/src/common/error/unauthorized.user.ballot.exception.ts
  BE/src/common/typeorm/typeorm.config.ts
  BE/src/event/event-client.model.ts
  BE/src/game-room/entity/game-chat.model.ts
  BE/src/game-room/entity/game-client.model.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game-room/entity/game-room.status.ts
  BE/src/game-room/game-room.service.ts
  BE/src/game-user/entity/game-user.entity.ts
  BE/src/game-user/entity/game-user.result.ts
  BE/src/game-user/game-user.module.ts
  BE/src/game-user/game-user.service.ts
  BE/src/game-user/repository/typeorm.game-user.repository.ts
  BE/src/game-user/usecase/find.game-user.usecase.ts
  BE/src/game/dto/allocate.job.request.ts
  BE/src/game/dto/start.countdown.request.ts
  BE/src/game/dto/stop.countdown.request.ts
  BE/src/game/entity/game-history.entity.ts
  BE/src/game/game.module.ts
  BE/src/game/game.service.ts
  BE/src/game/job.factory.ts
  BE/src/game/usecase/allocate-user-role/allocate.user-role.service.ts
  BE/src/game/usecase/allocate-user-role/allocate.user-role.usecase.ts
  BE/src/game/usecase/allocate-user-role/job.factory.ts
  BE/src/game/usecase/allocate-user-role/random.job.factory.ts
  BE/src/game/usecase/allocate.user-role.usecase.ts
  BE/src/game/usecase/countdown/countdown.timeout.service.ts
  BE/src/game/usecase/countdown/countdown.timeout.usecase.ts
  BE/src/game/usecase/countdown/countdown.timer.ts
  BE/src/game/usecase/countdown/mafia.countdown.timer.ts
  BE/src/game/usecase/game-manager/game-manager.ts
  BE/src/game/usecase/game-manager/total.game-manager.ts
  BE/src/game/usecase/game-manager/vote.mafia.service.ts
  BE/src/game/usecase/game-manager/vote.mafia.usecase.ts
  BE/src/game/user-status.ts
  BE/src/user/entity/user.entity.ts
Labels: be, D-1, feat

#124 [Feat] 유한 상태 기계 기반 게임 진행 기능 개발
  BE/src/event/event.gateway.ts
  BE/src/event/event.module.ts
  BE/src/game-room/entity/game-client.model.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game-room/game-room.module.ts
  BE/src/game-room/game-room.service.ts
  BE/src/game/fsm/game-context.ts
  BE/src/game/fsm/states/argument.state.ts
  BE/src/game/fsm/states/discussion.state.ts
  BE/src/game/fsm/states/doctor.state.ts
  BE/src/game/fsm/states/mafia.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/fsm/states/set-up.state.ts
  BE/src/game/fsm/states/state.ts
  BE/src/game/fsm/states/vote.state.ts
  BE/src/game/game.module.ts
  BE/src/game/timeout.situation.ts
  BE/src/game/usecase/countdown/countdown.timeout.service.ts
  BE/src/game/usecase/countdown/countdown.timer.ts
  BE/src/game/usecase/countdown/mafia.countdown.timer.ts
  BE/src/game/usecase/start-game/start-game.service.ts
  BE/src/game/usecase/start-game/start-game.usecase.ts
  BE/src/video-server/types/openvidu.type.ts
Labels: be, D-1, feat

#119 [Refactor] 오디오/비디오 on/off 여부 표시
  .github/workflows/deploy_FE.yml
  FE/__tests__/LobbyItem.test.tsx
  FE/__tests__/useOpenVidu.test.ts
  FE/jest.config.ts
  FE/jest.setup.ts
  FE/package-lock.json
  FE/package.json
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/hooks/useOpenVidu.ts
  FE/src/stores/sidebarStore.ts
  FE/src/stores/socketStore.ts
  FE/src/types/gamePublisher.ts
  FE/src/types/gameSubscriber.ts
Labels: fe, D-2, refactor, test

#125 [Test] 로비 페이지, 게임 시작 E2E 테스트
  FE/.gitignore
  FE/__tests__/socketStore.test.ts
  FE/__tests__/useOpenVidu.test.ts
  FE/jest.config.ts
  FE/package-lock.json
  FE/package.json
  FE/playwright.config.ts
  FE/src/components/game/Bottombar.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/lobby/NicknameModal.tsx
  FE/tests/lobby.test.ts
  FE/tests/openvidu.test.ts
Labels: fe, D-2, test, chore

#128 [Fix] 프론트엔드 CI/CD 오류 수정
  .github/workflows/deploy_FE.yml
Labels: fix, fe

#129 [Fix] 프론트엔드 CI/CD 수정
  .github/workflows/deploy_FE.yml
Labels: fix, fe

#133 [Feat] 마피아 동료 정보 전달방식 변경
  BE/src/game/usecase/allocate-user-role/random.job.factory.ts
Labels: be, D-0, feat

#134 [Feat] 직업 확인 기능
  FE/package-lock.json
  FE/package.json
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/constants/role.ts
  FE/src/constants/situation.ts
Labels: fe, D-0, feat, chore

#138 [Fix] 채팅 메세지 전송 오류 수정
  FE/src/components/game/ChattingList.tsx
  FE/tests/openvidu.test.ts
Labels: fix, fe, D-0

#139 [Feat] 경찰 기능 구현
  BE/src/event/event.gateway.ts
  BE/src/game/dto/police.investigation.request.ts
  BE/src/game/fsm/states/final-vote.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/fsm/states/primary-vote.state.ts
  BE/src/game/game.module.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/allocate-user-role/allocate.user-role.service.ts
  BE/src/game/usecase/role-playing/police-manager.ts
  BE/src/game/usecase/role-playing/police.investigate.service.ts
  BE/src/game/usecase/role-playing/police.investigate.usecase.ts
  BE/src/game/usecase/vote-manager/vote-manager.ts
  BE/src/game/usecase/vote-manager/vote.mafia.service.ts
  BE/src/game/usecase/vote-manager/vote.mafia.usecase.ts
Labels: be, D-1, feat

#140 [Feat] 투표 기능 구현
  FE/src/components/common/Header.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/ChattingItem.tsx
  FE/src/components/game/ChattingList.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/stores/sidebarStore.ts
  FE/src/types/gamePublisher.ts
  FE/src/types/gameSubscriber.ts
Labels: fe, D-1, feat

#154 [Fix] 1차 투표에서 무효표가 다수표일 때 밤으로 넘어가지 않고 최종 변론으로 넘어가는 문제 해결
  BE/src/game/total.game-manager.ts
Labels: fix, be, D-0

#148 [Feat] 경찰 기능 구현
  .github/workflows/deploy_FE.yml
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/hooks/useOpenVidu.ts
  FE/src/types/gamePublisher.ts
  FE/src/types/gameSubscriber.ts
Labels: fe, D-2, feat, refactor

#150 [Fix] 투표 기능 오류 수정
  FE/src/components/game/GameViewer.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/useOpenVidu.ts
Labels: fix, fe, D-2

#156 [Feat] 의사 임무 수행 기능 구현
  BE/package-lock.json
  BE/src/common/error/can-not.select.exception.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/not.found.mafia.kill.log.exception.ts
  BE/src/common/error/unauthorized.select.exception.ts
  BE/src/event/event.gateway.ts
  BE/src/game/dto/select.doctor.target.request.ts
  BE/src/game/dto/select.mafia.target.request.ts
  BE/src/game/fsm/states/doctor.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/game.module.ts
  BE/src/game/killOption-status.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/allocate-user-role/random.job.factory.ts
  BE/src/game/usecase/role-playing/doctor-manager.ts
  BE/src/game/usecase/role-playing/doctor.save.service.ts
  BE/src/game/usecase/role-playing/doctor.save.usecase.ts
  BE/src/game/usecase/role-playing/mafia-manager.ts
  BE/src/game/usecase/role-playing/mafia.kill.service.ts
  BE/src/game/usecase/role-playing/mafia.kill.usecase.ts
  BE/src/game/usecase/role-playing/police-manager.ts
Labels: be, D-1, feat

#155 [Feat] 마피아 기능 구현
  FE/next.config.ts
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/ChattingList.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/useOpenVidu.ts
Labels: fe, D-2, feat, ui

#152 [Feat] 카카오 OAuth Login 구현과 닉네임 변경 API 구현
  BE/package-lock.json
  BE/package.json
  BE/src/common/error/duplicate.nickname.exception.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/filter/global.exception.filter.ts
  BE/src/common/logger/http.logger.interceptor.ts
  BE/src/common/logger/sanitize.data.ts
  BE/src/common/logger/websocket.logger.interceptor.ts
  BE/src/common/sql/schema.sql
  BE/src/user/controller/auth.controller.ts
  BE/src/user/controller/user.controller.ts
  BE/src/user/dto/register-user.request.ts
  BE/src/user/dto/register-user.response.ts
  BE/src/user/dto/update-nickname.request.ts
  BE/src/user/entity/user.entity.ts
  BE/src/user/repository/typeorm.user.repository.ts
  BE/src/user/repository/user.repository.ts
  BE/src/user/usecase/login.user.usecase.ts
  BE/src/user/usecase/update.user.usecase.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: be, D-2, feat

#161 [Feat] 인증/인가 구현과 관리자 로그인 구현
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/auth/auth.module.ts
  BE/src/auth/auth.service.ts
  BE/src/auth/guard/user-detail.jwt.guard.ts
  BE/src/auth/usecase/token.provide.usecase.ts
  BE/src/auth/usecase/token.verify.usecase.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/invalid.password.exception.ts
  BE/src/common/error/unauthorized.user.exception.ts
  BE/src/common/sql/schema.sql
  BE/src/main.ts
  BE/src/user/controller/auth.controller.ts
  BE/src/user/controller/user.controller.ts
  BE/src/user/dto/admin-login.request.ts
  BE/src/user/dto/register-admin.request.ts
  BE/src/user/dto/register-user.request.ts
  BE/src/user/entity/user.entity.ts
  BE/src/user/repository/typeorm.user.repository.ts
  BE/src/user/repository/user.repository.ts
  BE/src/user/usecase/find.user-info.usecase.ts
  BE/src/user/usecase/login.admin.usecase.ts
  BE/src/user/usecase/login.user.usecase.ts
  BE/src/user/usecase/register.admin.usecase.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: be, D-2, feat

#167 [Feat] 의사 기능 구현 & 관리자 로그인/회원가입 기능 구현
  FE/next.config.ts
  FE/src/app/api/login/admin/route.ts
  FE/src/app/signin/admin/page.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/signin/AdminPanel.tsx
  FE/src/components/signin/SigninPanel.tsx
  FE/src/constants/toastOption.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/libs/zod/accountCreateFormSchema.ts
Labels: fe, D-2, feat, ui

#170 [Feat] 게임 종료 상태 구현
  BE/src/event/event-client.model.ts
  BE/src/event/event.gateway.ts
  BE/src/game-room/entity/game-chat.model.ts
  BE/src/game-room/entity/game-client.model.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game-room/game-room.service.ts
  BE/src/game/fsm/states/citizen-win.state.ts
  BE/src/game/fsm/states/final-vote.state.ts
  BE/src/game/fsm/states/mafia-win.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/fsm/states/set-up.state.ts
  BE/src/game/game.module.ts
  BE/src/game/repository/game-history.repository.ts
  BE/src/game/repository/typeorm.game-history.repository.ts
  BE/src/game/timeout.situation.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/allocate-user-role/allocate.user-role.service.ts
  BE/src/game/usecase/countdown/mafia.countdown.timer.ts
  BE/src/game/usecase/finish-game/finish-game.manager.ts
  BE/src/game/usecase/finish-game/finish-game.service.ts
  BE/src/game/usecase/finish-game/finish-game.usecase.ts
  BE/src/game/usecase/role-playing/police-manager.ts
  BE/src/game/usecase/role-playing/police.investigate.service.ts
  BE/src/game/usecase/role-playing/police.investigate.usecase.ts
Labels: fix, be, D-0, feat

#163 [Test] RandomJobFactory 테스트 코드 작성
  BE/package.json
  BE/test/game/usecase/allocate-user-role/random.job.factory.test.ts
  BE/tsconfig.json
Labels: be, D-3, test

#173 [Fix] MutexMap 빈 생성자 제거
  BE/src/common/utils/mutex-map.ts
  BE/src/user/controller/user.controller.ts
  BE/src/user/entity/user.entity.ts
Labels: fix, be, D-0

#177 [Fix] GameRoom 생성자 문제 해결
  BE/test/game/usecase/allocate-user-role/random.job.factory.test.ts
Labels: fix, be, D-0

#178 [Feat] 게임 진행 완성 & 로그아웃 기능
  FE/next.config.ts
  FE/src/app/api/login/admin/route.ts
  FE/src/app/api/signin/admin/route.ts
  FE/src/app/api/signout/admin/route.ts
  FE/src/app/api/user/info/route.ts
  FE/src/app/signin/admin/page.tsx
  FE/src/app/signin/page.tsx
  FE/src/components/common/Header.tsx
  FE/src/components/common/HeaderSidebar.tsx
  FE/src/components/game/ChattingList.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/signin/AdminPanel.tsx
  FE/src/components/signin/AuthPanel.tsx
  FE/src/components/signin/SigninPanel.tsx
  FE/src/components/signin/admin/AdminInput.tsx
  FE/src/components/signin/admin/AdminPanel.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/useChatting.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/hooks/useSignout.ts
  FE/src/middleware.ts
  FE/src/types/authAdmin.ts
  FE/src/types/room.ts
  FE/src/types/user.ts
Labels: fe, D-0, feat, refactor

#180 [Fix] 로그인 이후 로비 페이지로 접근하지 못하는 오류 수정
  FE/src/components/signin/admin/AdminPanel.tsx
  FE/src/hooks/useSignout.ts
Labels: fix, fe, D-0

#184 [Fix] 메인 페이지에서 새로고침을 통해 로그인한 사용자가 로비 페이지에 접속하지 못하는 오류 수정
  .github/workflows/deploy_FE.yml
  FE/src/components/common/Header.tsx
  FE/src/components/common/HeaderSidebar.tsx
  FE/src/components/home/Introduction.tsx
Labels: fix, fe, D-2

#166 [Test] 카운트다운 타이머 테스트
  BE/test/game/usecase/countdown/countdown.timeout.service.test.ts
  BE/test/game/usecase/countdown/mafia.countdown.timer.test.ts
Labels: be, D-3, test

#189 [Feat] LockManager 구현과 동시성 제어 변경
  BE/src/common/utils/lock-manager.ts
  BE/src/common/utils/mutex-map.ts
  BE/src/game/fsm/states/set-up.state.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/countdown/mafia.countdown.timer.ts
  BE/src/game/usecase/role-playing/mafia-manager.ts
  BE/src/game/usecase/role-playing/mafia.kill.service.ts
  BE/src/game/usecase/role-playing/mafia.kill.usecase.ts
Labels: be, D-2, feat

#198 [Fix] Guard에서 payLoad, body 타입 변경
  BE/src/auth/guard/user-detail.jwt.guard.ts
Labels: fix, be, D-1

#200 [Fix] openvidu 세션 종료 함수 에러 해결
  BE/src/video-server/implementations/openvidu.service.ts
Labels: fix, be, D-1

#193 [Feat] Docker를 활용한 Front-end CI/CD 구축
  .github/workflows/deploy_FE.yml
  FE/Dockerfile
Labels: fe, D-2, feat

#210 [Feat] Quick Start 시 빈방 Id 조회 API 구현
  BE/src/auth/guard/common.jwt.guard.ts
  BE/src/game-room/controller/game-room.controller.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game-room/game-room.module.ts
  BE/src/game-room/game-room.service.ts
Labels: be, D-1, feat

#214 [Fix] Front-end CI/CD 파이프라인 오류 수정
  .github/workflows/deploy_FE.yml
Labels: fix, fe, D-0

#211 [Feat] 특정 단계 카운트 다운 시작 이벤트 추가
  BE/src/game/usecase/countdown/mafia.countdown.timer.ts
Labels: be, D-1, feat

#215 [Feat] 방장 위임 기능 구현
  BE/src/event/event.gateway.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game-room/game-room.service.ts
  BE/src/game/fsm/states/citizen-win.state.ts
  BE/src/game/fsm/states/doctor.state.ts
  BE/src/game/fsm/states/mafia-win.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/role-playing/police.investigate.service.ts
  BE/src/game/usecase/role-playing/police.investigate.usecase.ts
Labels: fix, be, D-2, feat

#199 [Feat] 닉네임 변경 기능 구현
  FE/__tests__/socketStore.test.ts
  FE/src/app/api/user/nickname/route.ts
  FE/src/app/layout.tsx
  FE/src/components/common/header/Header.tsx
  FE/src/components/common/header/HeaderSidebar.tsx
  FE/src/components/common/header/NicknameModal.tsx
  FE/src/components/common/header/ProfileModal.tsx
  FE/src/components/game/VideoItem.tsx
  FE/src/components/game/VideoViewer.tsx
  FE/src/components/home/Introduction.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/lobby/NicknameModal.tsx
  FE/src/components/signin/admin/AdminPanel.tsx
  FE/src/components/signin/loading/AuthLoading.tsx
  FE/src/hooks/useChatting.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/hooks/useSignout.ts
  FE/src/libs/zod/nicknameChangeFormSchema.ts
  FE/src/stores/authStore.ts
  FE/src/stores/sidebarStore.ts
  FE/src/stores/socketStore.ts
Labels: fe, D-2, feat, ui, refactor

#202 [Feat] 게임 방 개설자만 게임 시작을 할 수 있는 기능 & 코드 리팩토링
  FE/public/lottie/pulse.json
  FE/src/app/introduction/page.tsx
  FE/src/components/common/Footer.tsx
  FE/src/components/common/header/Header.tsx
  FE/src/components/common/header/HeaderSidebar.tsx
  FE/src/components/common/header/NicknameModal.tsx
  FE/src/components/common/header/ProfileModal.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/chatting/ChattingItem.tsx
  FE/src/components/game/chatting/ChattingList.tsx
  FE/src/components/game/video/InvalidityButton.tsx
  FE/src/components/game/video/VideoFilter.tsx
  FE/src/components/game/video/VideoItem.tsx
  FE/src/components/game/video/VideoViewer.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/NicknameModal.tsx
  FE/src/components/signin/loading/AuthLoading.tsx
  FE/src/constants/gameStatus.ts
  FE/src/hooks/useModalBackHandler.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/hooks/useScrollLock.ts
  FE/src/types/gamePublisher.ts
  FE/src/types/gameSubscriber.ts
Labels: fe, D-2, feat, ui, refactor, rename, remove

#217 [Feat] 게임 결과 표시 컴포넌트 구현 & Quick Start 기능 구현 & 방장 표시 기능 & 방장 변경 기능 & 빌드 방식 변경
  .github/workflows/deploy_FE.yml
  FE/Dockerfile
  FE/next.config.ts
  FE/src/app/api/rooms/vacant/route.ts
  FE/src/components/common/header/Header.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/GameResultBoard.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/video/InvalidityButton.tsx
  FE/src/components/game/video/VideoItem.tsx
  FE/src/components/game/video/VideoViewer.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/constants/gameStatus.ts
  FE/src/constants/roomStatus.ts
  FE/src/constants/situation.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/types/gamePublisher.ts
  FE/src/types/gameSubscriber.ts
  FE/src/types/room.ts
Labels: fix, fe, D-2, feat, ui

#219 [Feat] 게임 재시작 기능 & 방장 변경 알림 기능
  FE/src/components/game/GameResultBoard.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/hooks/useOpenVidu.ts
Labels: fe, D-2, feat

#223 [Feat] 웹소켓 커넥션을 연결할 때 헤더에 담긴 토큰으로 유저 정보를 조회하는 기능 구현
  BE/src/event/event-client.model.ts
  BE/src/event/event.gateway.ts
  BE/src/event/event.module.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game/total.game-manager.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: fix, be, D-2, feat

#225 [Feat] 게임 방 페이지에서 새로고침을 하거나 브라우저 탭을 닫을 때 방 퇴장 기능 구현
  FE/src/app/api/signin/admin/route.ts
  FE/src/app/api/signin/kakao/route.ts
  FE/src/components/common/header/Header.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/home/Introduction.tsx
  FE/src/components/lobby/ConnectedUserList.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/signin/AuthPanel.tsx
  FE/src/components/signin/loading/AuthLoading.tsx
  FE/src/hooks/useChatting.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/stores/authStore.ts
  FE/src/stores/sidebarStore.ts
  FE/src/stores/socketStore.ts
Labels: fe, D-2, feat, ui, refactor

#227 [Fix] 프론트엔드 env 설정 오류 수정
  FE/Dockerfile
Labels: fix, fe, D-0

#228 [Fix] env 설정 오류 수정
  FE/Dockerfile
Labels: fix, fe, D-0

#216 [Feat] log filter 구현과 log ncloud object storage 적재
  BE/package-lock.json
  BE/package.json
  BE/src/common/filter/http.exception.filter.ts
  BE/src/common/filter/websocket.exception.filter.ts
  BE/src/common/logger/websocket.logger.interceptor.ts
  BE/src/common/logger/winston.config.ts
  BE/src/common/object/ncloud.log.transport.ts
  BE/src/event/event.gateway.ts
  BE/src/event/event.module.ts
  BE/src/game/fsm/game-context.ts
  BE/src/game/usecase/start-game/start-game.service.ts
  BE/src/game/usecase/start-game/start-game.usecase.ts
  BE/src/main.ts
Labels: be, D-2, feat

#229 [Fix] deploy_FE.yml & Dockerfile 파일 수정
  .github/workflows/deploy_FE.yml
  FE/.dockerignore
  FE/Dockerfile
Labels: fix, fe, D-0

#232 [Refactor] CI/CD 배포 스크립트 수정
  .github/workflows/deploy_FE.yml
  FE/.dockerignore
  FE/Dockerfile
Labels: fe, D-0, refactor

#233 [Fix] env 설정 오류 수정
  .github/workflows/deploy_FE.yml
  FE/Dockerfile
Labels: fix, fe, D-0

#235 [Feat] 로비 페이지에서 카메라, 마이크 권한 요청 기능 구현
  .github/workflows/deploy_FE.yml
  FE/src/components/common/header/Header.tsx
  FE/src/components/common/header/HeaderSidebar.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/video/VideoFilter.tsx
  FE/src/components/home/Introduction.tsx
  FE/src/components/lobby/ConnectedUserList.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/lobby/NicknameModal.tsx
  FE/src/components/signin/AuthPanel.tsx
  FE/src/hooks/useOpenVidu.ts
  FE/src/hooks/usePermissionManager.ts
  FE/src/hooks/useSignout.ts
  FE/src/stores/authStore.ts
  FE/src/stores/participantListStore.ts
Labels: fe, D-1, feat, refactor

#237 [Feat] 유저 중복 로그인 제한 기능
  BE/src/common/error/duplicate.login-user.exception.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/event/event.gateway.ts
  BE/src/user/controller/auth.controller.ts
  BE/src/user/controller/user.controller.ts
  BE/src/user/dto/logout.request.ts
  BE/src/user/entity/user.entity.ts
  BE/src/user/usecase/find.user-info.usecase.ts
  BE/src/user/usecase/logout.usecase.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: be, D-0, feat

#239 [Feat] 유저 실시간 상태 관리 기능
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/event/event.const.ts
  BE/src/event/event.gateway.ts
  BE/src/event/event.module.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/role-playing/doctor.cure.service.ts
  BE/src/game/usecase/role-playing/doctor.cure.usecase.ts
  BE/src/online-state/connected-user.service.ts
  BE/src/online-state/connected-user.usecase.ts
  BE/src/online-state/dto/user.connect.request.ts
  BE/src/online-state/online-state.module.ts
  BE/src/redis/io-user.usecase.ts
  BE/src/redis/redis.module.ts
  BE/src/redis/redis.service.ts
  BE/src/user/user.module.ts
  BE/src/user/user.service.ts
Labels: be, D-1, feat

#240 [Feat] 방 참가자 정보 수동 조회 API 구현
  BE/src/event/event.gateway.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game-room/game-room.service.ts
Labels: be, D-1, feat, refactor

#242 [Fix] 닉네임 수정 오류와 유저 탭 공유 예외 수정
  BE/src/user/user.service.ts
Labels: fix, be, D-0

#244 [Feat] 유저 실시간 접속 상태 표시 기능
  FE/src/app/api/cookie/route.ts
  FE/src/app/api/signout/route.ts
  FE/src/app/api/user/info/route.ts
  FE/src/app/api/user/nickname/route.ts
  FE/src/components/common/header/Header.tsx
  FE/src/components/common/header/NicknameModal.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/chatting/ChattingItem.tsx
  FE/src/components/game/chatting/ChattingList.tsx
  FE/src/components/lobby/ConnectedUserList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/signin/admin/AdminPanel.tsx
  FE/src/components/signin/loading/AuthLoading.tsx
  FE/src/hooks/useChatting.ts
  FE/src/hooks/useConnectedUserList.ts
  FE/src/hooks/useOpenVidu.ts
  FE/src/hooks/useSignout.ts
  FE/src/stores/connectedUserListStore.ts
  FE/src/types/chat.ts
Labels: fix, fe, D-0, feat, ui
