Repository boostcampwm-2024/web12-MafiaCamp, pull requests merged in 2024-12, with the labels that each got.

#251 [Docs] README 업데이트
  README.md
Labels: D-0, docs

#253 [Docs] README에 gif 추가
  README.md
Labels: D-0, docs

#255 [Docs] README.md 업데이트
  README.md
Labels: D-0, docs

#258 [FE] FE_develop에서 develop으로 merge
  FE/__tests__/useOpenVidu.test.ts
  FE/public/common/globe.png
  FE/public/lottie/global.json
  FE/src/components/common/FloatingButton.tsx
  FE/src/components/common/Footer.tsx
  FE/src/components/common/header/Header.tsx
  FE/src/components/common/header/HeaderSidebar.tsx
  FE/src/components/common/header/NicknameModal.tsx
  FE/src/components/common/header/ProfileModal.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/GameViewer.tsx
  FE/src/components/game/chatting/ChattingForm.tsx
  FE/src/components/game/chatting/ChattingHeader.tsx
  FE/src/components/game/chatting/ChattingList.tsx
  FE/src/components/game/chatting/ChattingPanel.tsx
  FE/src/components/game/video/InvalidityButton.tsx
  FE/src/components/game/video/VideoItem.tsx
  FE/src/components/game/video/VideoViewer.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/components/lobby/LobbyList.tsx
  FE/src/components/lobby/LobbyViewer.tsx
  FE/src/components/signin/admin/AdminInput.tsx
  FE/src/components/signin/admin/AdminPanel.tsx
  FE/src/components/signin/loading/AuthLoading.tsx
  FE/src/hooks/common/useAutoSignin.ts
  FE/src/hooks/common/useConnectedUserList.ts
  FE/src/hooks/common/useHeaderController.ts
  FE/src/hooks/common/useNicknameManager.ts
  FE/src/hooks/common/useSignout.ts
  FE/src/hooks/game/chatting/useChattingForm.ts
  FE/src/hooks/game/chatting/useChattingList.ts
  FE/src/hooks/game/useGameStatus.ts
  FE/src/hooks/game/useOpenVidu.ts
  FE/src/hooks/lobby/useLobbyList.ts
  FE/src/hooks/lobby/usePermissionManager.ts
  FE/src/hooks/lobby/useRoomManager.ts
  FE/src/hooks/signin/useAuthForm.ts
  FE/src/hooks/useChatting.ts
  FE/src/hooks/utils/useDragScroll.ts
  FE/src/hooks/utils/useModalBackHandler.ts
  FE/src/hooks/utils/useScrollLock.ts
Labels: fe, D-0

#260 [Feat] 닉네임 변경 시, EventClient로 반영되도록 설정
  BE/src/event/event-client-manager.ts
  BE/src/event/event.gateway.ts
  BE/src/event/event.module.ts
  BE/src/user/user.service.ts
Labels: be, D-0, bug

#263 [Fix] 이벤트 구독 로직 수정
  BE/src/event/event-manager.ts
Labels: fix, be, D-1

#264 [Fix] 댓글창 오류 수정 & 가로 스크롤이 생기는 오류 수정
  BE/package-lock.json
  FE/src/app/layout.tsx
  FE/src/components/game/chatting/ChattingList.tsx
  FE/src/components/game/chatting/ChattingPanel.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/game/useGameStatus.ts
  FE/src/hooks/game/useOpenVidu.ts
  README.md
Labels: fix, fe, D-0

#266 [Fix] UserId type 문제와 eventClient.nickname 선언 문제 해결
  BE/src/event/event-client-manager.ts
  BE/src/user/user.service.ts
Labels: fix, be, D-0

#268 [Feat] 닉네임 변경 시 소켓 재연결 기능
  FE/src/app/layout.tsx
  FE/src/components/common/header/Header.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/hooks/common/useNicknameManager.ts
Labels: fe, D-1, feat

#273 [BE] 게임 중간 탈주 계산 구현
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/not.found.doctor.exception.ts
  BE/src/common/error/not.found.police.exception.ts
  BE/src/common/logger/winston.config.ts
  BE/src/event/event.gateway.ts
  BE/src/game/dto/detect.early.quit.request.ts
  BE/src/game/fsm/game-context.manager.ts
  BE/src/game/fsm/game-context.ts
  BE/src/game/fsm/states/argument.state.ts
  BE/src/game/fsm/states/citizen-win.state.ts
  BE/src/game/fsm/states/discussion.state.ts
  BE/src/game/fsm/states/doctor.state.ts
  BE/src/game/fsm/states/final-vote.state.ts
  BE/src/game/fsm/states/mafia-win.state.ts
  BE/src/game/fsm/states/mafia.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/fsm/states/primary-vote.state.ts
  BE/src/game/fsm/states/state.ts
  BE/src/game/game.module.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/allocate-user-role/random.job.factory.ts
  BE/src/game/usecase/detect-early-quit/detect.early.quit.service.ts
  BE/src/game/usecase/detect-early-quit/detect.early.quit.usecase.ts
  BE/src/game/usecase/detect-early-quit/detect.manager.ts
  BE/src/game/usecase/finish-game/finish-game.service.ts
  BE/src/game/usecase/finish-game/finish-game.usecase.ts
  BE/src/game/usecase/start-game/start-game.service.ts
  BE/src/user/controller/user.controller.ts
Labels: be, D-0, feat

#279 [Docs] README 업데이트
  README.md
Labels: D-0, docs

#283 [Feat] 1차 투표와 최종 투표 구분 & 카운트다운 시계 소리 볼륨 조정
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/video/VideoFilter.tsx
  FE/src/components/game/video/VideoItem.tsx
  FE/src/components/game/video/VideoViewer.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/game/useGameStatus.ts
  FE/src/hooks/game/useTickingTimerAudio.ts
  FE/src/hooks/game/video/useVideoItem.ts
Labels: fe, D-0, feat, ui

#284 [Fix] 게임 재시작 시 마피아 전용 채팅 이벤트 중복 발생 문제 해결
  BE/src/event/event.gateway.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game/total.game-manager.ts
Labels: fix, be, D-0

#287 [Fix] 게임 중복 실행 제한
  BE/src/common/error/duplicate.game-context.exception.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/game/fsm/game-context.manager.ts
Labels: fix, be, D-0

#288 [Feat] 버튼 이벤트 중복 호출 방지 기능 구현
  FE/src/components/game/Bottombar.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/hooks/game/useGameStatus.ts
  FE/src/hooks/lobby/useLobbyList.ts
  FE/src/hooks/lobby/useRoomManager.ts
  FE/src/hooks/utils/useThrottle.ts
Labels: fix, fe, D-1, feat

#291 [Docs] README 업데이트
  README.md
Labels: D-0, docs

#292 [FE] FE_develop에서 develop으로 merge
  FE/public/ticking_timer.mp3
  FE/src/app/layout.tsx
  FE/src/components/common/header/Header.tsx
  FE/src/components/game/Bottombar.tsx
  FE/src/components/game/chatting/ChattingList.tsx
  FE/src/components/game/chatting/ChattingPanel.tsx
  FE/src/components/game/video/VideoFilter.tsx
  FE/src/components/game/video/VideoItem.tsx
  FE/src/components/game/video/VideoViewer.tsx
  FE/src/components/lobby/CreateRoomModal.tsx
  FE/src/components/lobby/LobbyBanner.tsx
  FE/src/components/lobby/LobbyItem.tsx
  FE/src/constants/situation.ts
  FE/src/hooks/common/useNicknameManager.ts
  FE/src/hooks/game/useGameStatus.ts
  FE/src/hooks/game/useOpenVidu.ts
  FE/src/hooks/game/useTickingTimerAudio.ts
  FE/src/hooks/game/video/useVideoItem.ts
  FE/src/hooks/lobby/useLobbyList.ts
  FE/src/hooks/lobby/useRoomManager.ts
  FE/src/hooks/utils/useThrottle.ts
Labels: fe, D-0

#293 [BE] BE_develop에서 develop으로 merge
  BE/src/common/error/duplicate.game-context.exception.ts
  BE/src/common/error/exception.code.ts
  BE/src/common/error/exception.message.ts
  BE/src/common/error/not.found.doctor.exception.ts
  BE/src/common/error/not.found.police.exception.ts
  BE/src/common/logger/winston.config.ts
  BE/src/event/event-client-manager.ts
  BE/src/event/event-manager.ts
  BE/src/event/event.gateway.ts
  BE/src/event/event.module.ts
  BE/src/game-room/entity/game-room.model.ts
  BE/src/game/dto/detect.early.quit.request.ts
  BE/src/game/fsm/game-context.manager.ts
  BE/src/game/fsm/game-context.ts
  BE/src/game/fsm/states/argument.state.ts
  BE/src/game/fsm/states/citizen-win.state.ts
  BE/src/game/fsm/states/discussion.state.ts
  BE/src/game/fsm/states/doctor.state.ts
  BE/src/game/fsm/states/final-vote.state.ts
  BE/src/game/fsm/states/mafia-win.state.ts
  BE/src/game/fsm/states/mafia.state.ts
  BE/src/game/fsm/states/police.state.ts
  BE/src/game/fsm/states/primary-vote.state.ts
  BE/src/game/fsm/states/state.ts
  BE/src/game/game.module.ts
  BE/src/game/total.game-manager.ts
  BE/src/game/usecase/allocate-user-role/random.job.factory.ts
  BE/src/game/usecase/detect-early-quit/detect.early.quit.service.ts
  BE/src/game/usecase/detect-early-quit/detect.early.quit.usecase.ts
  BE/src/game/usecase/detect-early-quit/detect.manager.ts
  BE/src/game/usecase/finish-game/finish-game.service.ts
  BE/src/game/usecase/finish-game/finish-game.usecase.ts
  BE/src/game/usecase/start-game/start-game.service.ts
  BE/src/user/controller/user.controller.ts
  BE/src/user/user.service.ts
Labels: be, D-0
